export const productsDB = {
  1: {
    id: 1,
    category: 'spirits',
    title: 'Limited Edition 2022',
    description: 'Only 6000 bottles',
    price: '46.00',
    outOfStock: true,
    discount: '',
    limitedEdition: true,
    images: [
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/1/1_1.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/1/1_2.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/1/1_3.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/1/1_4.jpg',
    ],
    imageThumbnail:
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/1/1_thumbnail.jpg',
    text: '50cl / 45% / New recipe. Limited edition "Color Series"',
    formats: [
      { id: 1, text: '50cl', promotion: false },
      { id: 2, text: '6 x 50cl', promotion: true },
    ],
  },
  2: {
    id: 2,
    category: 'giftbox',
    title: 'Panda Giftbox',
    description: 'Everything you need',
    price: '67.00',
    outOfStock: false,
    discount: '',
    limitedEdition: false,
    images: [
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/2/2_1.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/2/2_2.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/2/2_3.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/2/2_4.jpg',
    ],
    imageThumbnail:
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/2/2_thumbnail.jpg',
    text: 'Giftbox contains: 1 bottle of Panda Gin of 50 cl, 2 Premium glasses, 1 playing cards and 1 book of cocktails',
    formats: [],
  },
  3: {
    id: 3,
    category: 'spirits',
    title: 'Panda Gin',
    description: '50CL / 40% VOL',
    price: '38.00',
    outOfStock: false,
    discount: '10',
    limitedEdition: false,
    images: [
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/3/3_1.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/3/3_2.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/3/3_3.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/3/3_4.jpg',
    ],
    imageThumbnail:
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/3/3_thumbnail.jpg',
    text: 'Mix 4 cl of Panda Gin with 12 cl of premium Indian tonic and decorate according to your personal inspiration',
    formats: [
      { id: 1, text: '50cl', promotion: false },
      { id: 2, text: '6 x 50cl', promotion: true },
    ],
  },
  4: {
    id: 4,
    category: 'spirits',
    title: 'Big Panda',
    description: '1 LITER / 40% VOL',
    price: '74.00',
    outOfStock: false,
    discount: '',
    limitedEdition: false,
    images: [
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/4/4_1.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/4/4_2.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/4/4_3.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/4/4_4.jpg',
    ],
    imageThumbnail:
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/4/4_thumbnail.jpg',
    text: 'Mix 4 cl of Panda Gin with 12 cl of premium indian tonic and decorate according to your personal inspiration',
    formats: [
      { id: 1, text: '100cl', promotion: false },
      { id: 2, text: '6 x 100cl', promotion: true },
    ],
  },
  5: {
    id: 5,
    category: 'spirits',
    title: 'Panda Gin x Denis Meyers',
    description: 'Only 10.000 bottles',
    price: '38.00',
    outOfStock: false,
    discount: '',
    limitedEdition: true,
    images: [
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/5/5_1.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/5/5_2.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/5/5_3.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/5/5_4.jpg',
    ],
    imageThumbnail:
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/5/5_thumbnail.jpg',
    text: 'Discover Panda Gin first collaboration with artist Denis Meyers',
    formats: [
      { id: 1, text: '50cl', promotion: false },
      { id: 2, text: '6 x 50cl', promotion: true },
    ],
  },
  6: {
    id: 6,
    category: 'spirits',
    title: 'Baby Panda',
    description: '5cl / 40% VOL',
    price: '7.20',
    outOfStock: false,
    discount: '',
    limitedEdition: false,
    images: [
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/6/6_1.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/6/6_2.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/6/6_3.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/6/6_4.jpg',
    ],
    imageThumbnail:
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/6/6_thumbnail.jpg',
    text: 'Mini bottle Panda Gin 5cl ',
    formats: [
      { id: 1, text: '5cl', promotion: false },
      { id: 2, text: '6 x 5cl', promotion: true },
    ],
  },
  7: {
    id: 7,
    category: 'giftbox',
    title: 'Premium Glass',
    description: 'Matt white glass',
    price: '8.95',
    outOfStock: false,
    discount: '',
    limitedEdition: false,
    images: [
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/7/7_1.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/7/7_2.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/7/7_3.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/7/7_4.jpg',
    ],
    imageThumbnail:
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/7/7_thumbnail.jpg',
    text: 'Drink your Panda tonic with the perfect premium glass for a perfect moment.',
    formats: [],
  },
  8: {
    id: 8,
    category: 'giftbox',
    title: 'Mini Giftbox',
    description: 'Small but cute',
    price: '13.95',
    outOfStock: false,
    discount: '15',
    limitedEdition: false,
    images: [
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/8/8_1.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/8/8_2.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/8/8_3.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/8/8_4.jpg',
    ],
    imageThumbnail:
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/8/8_thumbnail.jpg',
    text: 'Baby bottle & unbreakable Cup',
    formats: [],
  },
  9: {
    id: 9,
    category: 'goodies',
    title: 'Panda Glass',
    description: 'Clear Glass',
    price: '6.95',
    outOfStock: true,
    discount: '',
    limitedEdition: false,
    images: [
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/9/9_1.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/9/9_2.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/9/9_3.jpg',
    ],
    imageThumbnail:
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/9/9_thumbnail.jpg',
    text: 'Perfect serve',
    formats: [],
  },
  10: {
    id: 10,
    category: 'clothing',
    title: 'Hoodie Panda',
    description: 'Have panda style',
    price: '40.00',
    outOfStock: false,
    discount: '',
    limitedEdition: false,
    images: [
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/10/10_1.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/10/10_2.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/10/10_3.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/10/10_4.jpg',
    ],
    imageThumbnail:
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/10/10_thumbnail.jpg',
    text: 'Woman / Men (UNISEX)',
    formats: [
      { id: 1, text: 'xs' },
      { id: 2, text: 's' },
      { id: 3, text: 'm' },
      { id: 4, text: 'l' },
      { id: 5, text: 'xl' },
      { id: 6, text: 'xxl' },
    ],
  },
  11: {
    id: 11,
    category: 'clothing',
    title: 'T-Shirt Panda',
    description: 'Be yourself',
    price: '23.00',
    outOfStock: false,
    discount: '',
    limitedEdition: false,
    images: [
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/11/11_1.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/11/11_2.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/11/11_3.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/11/11_4.jpg',
    ],
    imageThumbnail:
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/11/11_thumbnail.jpg',
    text: 'Woman / Men (UNISEX)',
    formats: [
      { id: 1, text: 'xs' },
      { id: 2, text: 's' },
      { id: 3, text: 'm' },
      { id: 4, text: 'l' },
      { id: 5, text: 'xl' },
      { id: 6, text: 'xxl' },
    ],
  },
  12: {
    id: 12,
    category: 'clothing',
    title: 'Beanie Panda',
    description: 'A classic',
    price: '19.00',
    outOfStock: false,
    discount: '5',
    limitedEdition: false,
    images: [
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/12/12_1.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/12/12_2.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/12/12_3.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/12/12_4.jpg',
    ],
    imageThumbnail:
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/12/12_thumbnail.jpg',
    text: 'Gray Panda hat and one size',
    formats: [],
  },
  13: {
    id: 13,
    category: 'goodies',
    title: 'Bar Mat Panda',
    description: 'Perfect service',
    price: '25.00',
    outOfStock: false,
    discount: '25',
    limitedEdition: false,
    images: [
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/13/13_1.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/13/13_2.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/13/13_3.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/13/13_4.jpg',
    ],
    imageThumbnail:
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/13/13_thumbnail.jpg',
    text: 'The Panda Gin bar mat should not be missing in the basic equipment of your bar!',
    formats: [],
  },
  14: {
    id: 14,
    category: 'goodies',
    title: 'Panda Candle',
    description: '300gr / 40H',
    price: '26.45',
    outOfStock: false,
    discount: '',
    limitedEdition: false,
    images: [
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/14/14_1.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/14/14_2.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/14/14_3.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/14/14_4.jpg',
    ],
    imageThumbnail:
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/14/14_thumbnail.jpg',
    text: 'A Panda candle in our 2021 recycled limited edition bottle.',
    formats: [],
  },
  15: {
    id: 15,
    category: 'goodies',
    title: 'Bundle Panda',
    description: 'Panda Gin 50cl + 1 candle',
    price: '55.00',
    outOfStock: false,
    discount: '',
    limitedEdition: false,
    images: [
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/15/15_1.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/15/15_2.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/15/15_3.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/15/15_4.jpg',
    ],
    imageThumbnail:
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/15/15_thumbnail.jpg',
    text: 'Discover our bundle with 1 Panda Gin 50cl bottle and 1 candle',
    formats: [],
  },
  16: {
    id: 16,
    category: 'goodies',
    title: 'Playing Cards Panda',
    description: 'Play with your friends',
    price: '5.00',
    outOfStock: false,
    discount: '',
    limitedEdition: false,
    images: [
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/16/16_1.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/16/16_2.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/16/16_3.jpg',
    ],
    imageThumbnail:
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/16/16_thumbnail.jpg',
    text: 'An original card game',
    formats: [],
  },
  17: {
    id: 17,
    category: 'goodies',
    title: 'Unbreakable Cup',
    description: 'Perfect summer serve',
    price: '6.00',
    outOfStock: false,
    discount: '15',
    limitedEdition: false,
    images: [
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/17/17_1.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/17/17_2.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/17/17_3.jpg',
    ],
    imageThumbnail:
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/17/17_thumbnail.jpg',
    text: 'For your perfect serve',
    formats: [],
  },
  18: {
    id: 18,
    category: 'goodies',
    title: 'Wooden coaster',
    description: 'The art of the table',
    price: '5.45',
    outOfStock: false,
    discount: '',
    limitedEdition: false,
    images: [
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/18/18_1.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/18/18_2.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/18/18_3.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/18/18_4.jpg',
    ],
    imageThumbnail:
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/18/18_thumbnail.jpg',
    text: 'Set of 4 wooden coaster.',
    formats: [],
  },
  19: {
    id: 19,
    category: 'goodies',
    title: 'Panda Bottle Opener',
    description: 'To open your premium tonic',
    price: '3.95',
    outOfStock: false,
    discount: '',
    limitedEdition: false,
    images: [
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/19/19_1.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/19/19_2.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/19/19_3.jpg',
    ],
    imageThumbnail:
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/19/19_thumbnail.jpg',
    text: 'With this bottle opener open all bottles.',
    formats: [],
  },
  20: {
    id: 20,
    category: 'spirits',
    title: 'Limited Edition 2020',
    description: 'Only 3000 bottles',
    price: '46.00',
    outOfStock: true,
    discount: '',
    limitedEdition: true,
    images: [
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/20/20_1.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/20/20_2.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/20/20_3.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/20/20_4.jpg',
    ],
    imageThumbnail:
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/20/20_thumbnail.jpg',
    text: '50cl / 45% / New recipe. Limited edition "Color Series"',
    formats: [
      { id: 1, text: '50cl', promotion: false },
      { id: 2, text: '6 x 50cl', promotion: true },
    ],
  },
  21: {
    id: 21,
    category: 'spirits',
    title: 'Limited Edition 2021',
    description: 'Only 5000 bottles',
    price: '46.00',
    outOfStock: true,
    discount: '',
    limitedEdition: true,
    images: [
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/21/21_1.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/21/21_2.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/21/21_3.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/21/21_4.jpg',
    ],
    imageThumbnail:
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/21/21_thumbnail.jpg',
    text: '50cl / 45% / New recipe. Limited edition "Color Series"',
    formats: [
      { id: 1, text: '50cl', promotion: false },
      { id: 2, text: '6 x 50cl', promotion: true },
    ],
  },
  22: {
    id: 22,
    category: 'goodies',
    title: 'Tote Bag',
    description: 'Always with you',
    price: '6.50',
    outOfStock: false,
    discount: '30',
    limitedEdition: false,
    images: [
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/22/22_1.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/22/22_2.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/22/22_3.jpg',
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/22/22_4.jpg',
    ],
    imageThumbnail:
      'https://raw.githubusercontent.com/Ajihat/panda-gin-images/main/22/22_thumbnail.jpg',
    text: 'A trendy bag for your shopping',
    formats: [],
  },
};
