const CLOSE_TOPSLIDER: string = "CLOSE_TOPSLIDER";
const OPEN_CURTAIN: string = "OPEN_CURTAIN";
const CLOSE_CURTAIN: string = "CLOSE_CURTAIN";
const SHOW_NAVBARS: string = "SHOW_NAVBARS";
const HIDE_NAVBARS: string = "HIDE_NAVBARS";
const OPEN_LOGINPOPUP: string = "OPEN_LOGINPOPUP";
const HIDE_LOGINPOPUP: string = "HIDE_LOGINPOPUP";




export { CLOSE_TOPSLIDER, OPEN_CURTAIN, CLOSE_CURTAIN, SHOW_NAVBARS, HIDE_NAVBARS, OPEN_LOGINPOPUP, HIDE_LOGINPOPUP }