const CLOSE_TOPSLIDER: string = "CLOSE_TOPSLIDER";
const OPEN_CURTAIN: string = "OPEN_CURTAIN";
const CLOSE_CURTAIN: string = "CLOSE_CURTAIN";
const SHOW_NAVBARS: string = "SHOW_NAVBARS";
const HIDE_NAVBARS: string = "HIDE_NAVBARS";
const OPEN_LOGIN_POPUP: string = "OPEN_LOGIN_POPUP";
const HIDE_LOGIN_POPUP: string = "HIDE_LOGIN_POPUP";
const OPEN_SUBSCRIBE_POPUP: string = "OPEN_SUBSCRIBE_POPUP";
const HIDE_SUBSCRIBE_POPUP: string = "HIDE_SUBSCRIBE_POPUP";





export { CLOSE_TOPSLIDER, OPEN_CURTAIN, CLOSE_CURTAIN, SHOW_NAVBARS, HIDE_NAVBARS, OPEN_LOGIN_POPUP, HIDE_LOGIN_POPUP, OPEN_SUBSCRIBE_POPUP, HIDE_SUBSCRIBE_POPUP }