export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const DELETE_PRODUCT_FROM_CART = "DELETE_PRODUCT_FROM_CART";
export const ADD_GIFT_TO_CART = "ADD_GIFT_TO_CART";
export const DELETE_GIFT_FROM_CART = "DELETE_GIFT_FROM_CART";
export const INCREASE_PRODUCT_QUANTITY = "INCREASE_PRODUCT_QUANTITY";
export const DECREASE_PRODUCT_QUANTITY = "DECREASE_PRODUCT_QUANTITY";
export const SET_GIFT_IS_CHOOSEN = "SET_GIFT_IS_CHOOSEN";
export const SET_GIFT_IS_NOT_CHOOSEN = "SET_GIFT_IS_NOT_CHOOSEN";
